
AE.namespace('AE.run.listing');AE.run.listing.countryRelatingProvince=new function(){_self=this;var dCountryItem,aSubItem,dProvinceItem,dCityItem;_self.create=function(id,mClass,bClass){var p=get(id);if(!p){return false;}
dCountryItem=YUD.getElementsByClassName(mClass,'a',p)[0];aSubItem=YUD.getElementsByClassName(bClass,'a',p);if(aSubItem.length>0){dCityItem=aSubItem[1];dProvinceItem=aSubItem[0];}
if(!aSubItem){return false;}
YUE.on(dCountryItem,'mouseover',countryOver);YUE.on(dCountryItem,'mouseout',countryOut);if(dCityItem){YUE.on(dProvinceItem,'mouseover',provinceOver);YUE.on(dProvinceItem,'mouseout',provinceOut);}}
var countryOver=function(){YUD.addClass(dCountryItem,'topOver');if(dCityItem){YUD.addClass(dProvinceItem,'midOver');YUD.addClass(dCityItem,'endOver');}else{YUD.addClass(dProvinceItem,'endOver');}}
var countryOut=function(){YUD.removeClass(dCountryItem,'topOver');YUD.removeClass(dProvinceItem,'midOver');YUD.removeClass(dProvinceItem,'endOver');YUD.removeClass(dCityItem,'endOver');}
var provinceOver=function(){YUD.addClass(dProvinceItem,'topOver');YUD.addClass(dCityItem,'endOver');}
var provinceOut=function(){YUD.removeClass(dProvinceItem,'topOver');YUD.removeClass(dCityItem,'endOver');}}
AE.run.listing.propertiyViewer=new function(){var _self=this;var oDefConfig={listContainerId:'particularListWrap',openClass:'openBtn',closeClass:'closeBtn',plusItemClass:'plusItem',itemTag:'li',itemOverClass:'over',showenItemCount:4,itemSize:[190,200],preBtnId:'particularViewerPre',nextBtnId:'particularViewerNext',fireFunction:YAHOO.util.Easing.easeBothStrong};var config;var dListContainer,aViewAll=[],aViewLess=[],allPlusItem=[],allIframe=[],allFixLine=[],allBlockItem=[],canHiddenAll=true,hiddened=true;var currentPageNum=1,pageCount=1,dAnimContainer,dFlowRind;var containerHeight;var dPreBtn,dNextBtn;var animPre,animNext;_self.create=function(oConfig){AE.run.listing.countryRelatingProvince.create('categoryHeadHint','relatedSpanM','relatedSpanB');config=AE.cpAttribute(oConfig,oDefConfig);dListContainer=get(config.listContainerId);dPreBtn=get(config.preBtnId);dNextBtn=get(config.nextBtnId);allBlockItem=YUD.getElementsByClassName('particularBlock','div',dListContainer);if(!allBlockItem||allBlockItem.length<=0){YUD.setStyle(get('particularListWrap'),'display','none');return false;}
var aLi=dListContainer.getElementsByTagName(config.itemTag);for(var i=0,n=aLi.length;i<n;i++){if(YUD.hasClass(aLi[i],config.openClass)){aViewAll.push(aLi[i]);}else if(YUD.hasClass(aLi[i],config.closeClass)){aViewLess.push(aLi[i]);}else{YUE.on(aLi[i],'click',function(ev,obj){location.href=obj.getElementsByTagName('a')[0].href;},aLi[i]);}
if(YUD.hasClass(aLi[i],config.plusItemClass)){allPlusItem.push(aLi[i]);}}
for(var i=0,n=allBlockItem.length;i<n;i++){if(i%4!=0){var d=document.createElement('div');allBlockItem[i].appendChild(d);YUD.addClass(d,'fixVLine');allFixLine.push(d);}}
for(var i=0,n=aViewAll.length,p,o,plusItem=[];i<n;i++){p=aViewAll[i].parentNode;var tmpIframe=document.createElement('iframe');YUD.addClass(tmpIframe,'maskIframe');tmpIframe.src='about:blank';p.parentNode.appendChild(tmpIframe);YUD.setStyle(tmpIframe,'display','none');plusItem=YUD.getElementsByClassName(config.plusItemClass,config.itemTag,p);YUE.on(aViewAll[i],'click',changeView,{hiddenItems:aViewAll[i],showenItems:[].concat(aViewLess[i],plusItem),pDiv:p,showMask:true,dThis:aViewAll[i]});YUE.on(aViewLess[i],'click',changeView,{hiddenItems:[].concat(aViewLess[i],plusItem),showenItems:aViewAll[i],pDiv:p,showMask:false,dThis:aViewAll[i]});}
allIframe=YUD.getElementsByClassName('maskIframe','iframe',dListContainer);YUE.on(document.body,'click',hiddenAll);var allItems=dListContainer.getElementsByTagName(config.itemTag);YUE.on(allItems,'mouseover',function(){YUD.addClass(this,config.itemOverClass);});YUE.on(allItems,'mouseout',function(){YUD.removeClass(this,config.itemOverClass);});YUE.on(dListContainer,'mouseover',function(){canHiddenAll=false;hiddened=false;});YUE.on(dListContainer,'mouseout',function(){canHiddenAll=true;});initAnim();resetTrueItem();switchBtnView();}
var changeView=function(ev,obj){forceHiddenAll();YUD.setStyle(obj.hiddenItems,'display','none');YUD.setStyle(obj.showenItems,'display','');var dIframe=YUD.getElementsByClassName('maskIframe','iframe',obj.pDiv.parentNode)[0];if(obj.showMask){YUD.setStyle(dIframe,'display','');YUD.setStyle(dIframe,'height',obj.pDiv.offsetHeight+'px');YUD.setStyle(dIframe,'width',obj.pDiv.offsetWidth+'px');YUD.setStyle(dIframe,'top','24px');YUD.replaceClass(obj.pDiv.parentNode,'lessViewStyle','moreViewStyle');var fixLine=YUD.getElementsByClassName('fixVLine','div',obj.pDiv.parentNode)[0];YUD.setStyle(fixLine,'display','none');}else{YUD.setStyle(dIframe,'display','none');YUD.replaceClass(obj.pDiv.parentNode,'moreViewStyle','lessViewStyle');}}
var forceHiddenAll=function(){forceHiddenAllIframe();YUD.setStyle([].concat(aViewLess,allPlusItem),'display','none');YUD.setStyle(aViewAll,'display','');YUD.setStyle(allFixLine,'display','');YUD.replaceClass(allBlockItem,'moreViewStyle','lessViewStyle');}
var hiddenAll=function(){if(!canHiddenAll&&!hiddened){return;}
forceHiddenAll();hiddened=true;}
var initAnim=function(){pageCount=Math.ceil(allBlockItem.length/4);var p=dListContainer.parentNode;var sHtml=[];dFlowRind=document.createElement('div');sHtml.push('<div "particularListWrap" id="particularListAnim">');sHtml.push('</div>');dFlowRind.innerHTML=sHtml.join('');p.appendChild(dFlowRind);var w=dListContainer.offsetWidth*3;containerHeight=dListContainer.offsetHeight;dAnimContainer=get('particularListAnim');YUD.setStyle(dAnimContainer,'width',w+'px');YUD.setStyle(dAnimContainer,'height',containerHeight+'px');YUD.setStyle(dFlowRind,'width',(dListContainer.offsetWidth-7)+'px');YUD.addClass(dFlowRind,'animFlowMask');resetAnimLayer();animPre=new YAHOO.util.Motion(dAnimContainer,{points:{by:[config.showenItemCount*config.itemSize[0],0]}},1,config.fireFunction)
animNext=new YAHOO.util.Motion(dAnimContainer,{points:{by:[-config.showenItemCount*config.itemSize[0],0]}},1,config.fireFunction)
animPre.onStart.subscribe(beforeAnim);animPre.onComplete.subscribe(afterAnim);animNext.onStart.subscribe(beforeAnim);animNext.onComplete.subscribe(afterAnim);YUD.setStyle(allBlockItem,'display','none');YUD.setStyle(dFlowRind,'display','none');YUE.on(dPreBtn,'mousedown',prePage);YUE.on(dNextBtn,'mousedown',nextPage);}
var fillAnimLayer=function(){dAnimContainer.innerHTML='';var sHtml=[];for(var i=config.showenItemCount*(currentPageNum-2);i<config.showenItemCount*(currentPageNum-2)+config.showenItemCount*3;i++){if(!allBlockItem[i]){sHtml.push('<div class="particularBlock lessViewStyle">&nbsp;</div>');}else{sHtml.push('<div class="'+allBlockItem[i].className+'">'+allBlockItem[i].innerHTML+'</div>');}}
dAnimContainer.innerHTML=sHtml.join('');}
var resetAnimLayer=function(){YUD.setStyle(dAnimContainer,'left',-config.showenItemCount*config.itemSize[0]+'px');fillAnimLayer();}
var resetTrueItem=function(){containerHeight=0;var iLength=config.showenItemCount*(currentPageNum-1);for(var i=iLength;i<iLength+config.showenItemCount;i++){if(allBlockItem[i]){YUD.setStyle(allBlockItem[i],'display','');containerHeight=(allBlockItem[i].getElementsByTagName('ul')[0].offsetHeight>containerHeight)?allBlockItem[i].getElementsByTagName('ul')[0].offsetHeight:containerHeight;}else{YUD.setStyle(allBlockItem[i],'display','none');}}
var tmpH=containerHeight+30;YUD.setStyle(dListContainer,'height',(tmpH-6)+'px');YUD.setStyle(dListContainer.parentNode,'height',(tmpH-20)+'px');YUD.setStyle(dFlowRind,'height',(tmpH-17)+'px');YUD.setStyle(allFixLine,'height',(tmpH-45)+'px');}
var prePage=function(){if(animPre.isAnimated()||animNext.isAnimated())return false;--currentPageNum;if(currentPageNum<1){currentPageNum=1;return false;}
animPre.animate();}
var nextPage=function(){if(animPre.isAnimated()||animNext.isAnimated())return false;++currentPageNum;if(currentPageNum>pageCount){currentPageNum=pageCount;return false;}
animNext.animate();}
var beforeAnim=function(){forceHiddenAllIframe();YUD.setStyle(dFlowRind,'display','');YUD.setStyle(allBlockItem,'display','none');switchBtnView();}
var forceHiddenAllIframe=function(){YUD.setStyle(allIframe,'display','none');}
var afterAnim=function(){resetTrueItem();YUD.setStyle(dFlowRind,'display','none');resetAnimLayer();}
var switchBtnView=function(){if(currentPageNum<=1){dPreBtn.className='disabledPrev';}else{dPreBtn.className='prev';}
if(currentPageNum>=pageCount){dNextBtn.className='disabledNext';}else{dNextBtn.className='next';}}}

AE.namespace('AE.run.listing');AE.run.listing.contactThem=function(){_self=this;_self.config={};var cboxs,contactContainer;var defConfig={checkboxName:'chkSellOfferIds',contactContainerId:'showContactThemBox',closeButtonId:'showContactClose',divClassName:'itemBox',divOverColor:'#F2F2F2'}
var showContactThemDiv=function(ev,args){var cbox=args['cbox'];var cindex=args['cindex'];var dv=YUD.getAncestorByClassName(cbox,'itemBox');if(cbox.checked==true){YUD.setStyle(dv,'background-color','#eaeaea');}else{YUD.setStyle(dv,'background-color','');}
var k=0;for(var i=0,len=cboxs.length;i<len;i++){if(cboxs[i].checked==true)k++;}
if(k>5&&cbox.checked==true){YUD.setStyle(contactContainer,'display','');var elXY=YUD.getXY(cbox);YUD.setXY(contactContainer,[elXY[0],elXY[1]-contactContainer.offsetHeight]);}else if(k>1){for(var t=cindex,len=cboxs.length;t<len;t++){if(cboxs[t].checked==true){var elXY=YUD.getXY(cboxs[t]);YUD.setXY(contactContainer,[elXY[0],elXY[1]-contactContainer.offsetHeight]);break;}}
for(var s=cindex,len=cindex+1;s>=0;s--){if(cboxs[s].checked==true){var elXY=YUD.getXY(cboxs[s]);YUD.setXY(contactContainer,[elXY[0],elXY[1]-contactContainer.offsetHeight]);break;}}}else if(k<=1){YUD.setStyle(contactContainer,'display','none');}}
var closeContactThemDiv=function(ev){YUD.setStyle(contactContainer,'display','none');}
var mouseOverDiv=function(ev,args){var cbox=cboxs[args.index];if(cbox.checked==true)return;var div=args.div;YUD.setStyle(this,'background-color',_self.config.divOverColor);}
var mouseOutDiv=function(ev,args){var cbox=cboxs[args.index];if(cbox.checked==true)return;var div=args.div;YUD.setStyle(div,'background-color','');}
_self.init=function(config){_self.config=YL.merge(defConfig,config);cboxs=document.getElementsByName(_self.config.checkboxName);contactContainer=get(_self.config.contactContainerId);var closeButton=get(_self.config.closeButtonId);for(var i=0,len=cboxs.length;i<len;i++){YUE.on(cboxs[i],'click',showContactThemDiv,{cbox:cboxs[i],cindex:i});}
YUE.on(closeButton,'click',closeContactThemDiv,contactContainer);divs=YUD.getElementsByClassName(_self.config.divClassName,'div');for(var i=0,len=divs.length;i<len;i++){YUE.on(divs[i],'mouseover',mouseOverDiv,{div:divs[i],index:i});YUE.on(divs[i],'mouseout',mouseOutDiv,{div:divs[i],index:i});}}}

AE.namespace('AE.run.listing');AE.run.listing.sortAttribute=function(){var _self=this;var sc=_self.config;var mItem;var bItem;_self.config={path:'categoryHeadHint',mClassName:'sortAttrsM',bClassName:'sortAttrsB',classTop:'topOver',classMid:'midOver',classEnd:'endOver'};var mOver=function(){YUD.addClass(mItem,sc.classTop);for(var i=0,len=bItem.length-1;i<len;i++){YUD.addClass(bItem[i],sc.classMid);}
YUD.addClass(bItem[len],sc.classEnd);}
var mOut=function(){YUD.removeClass(mItem,sc.classTop);for(var i=0,len=bItem.length-1;i<len;i++){YUD.removeClass(bItem[i],sc.classMid);}
YUD.removeClass(bItem[len],sc.classEnd);}
_self.init=function(config){sc=YL.merge(_self.config,config||{});bItem=YUD.getElementsByClassName(sc.bClassName,'a',sc.path);if(bItem.length>0){mItem=YUD.getElementsByClassName(sc.mClassName,'a',sc.path);YUE.on(mItem,'mouseover',mOver);YUE.on(mItem,'mouseout',mOut);}}}
